export const HTTP_STATUS_OK = 'Success'; // 200
export const HTTP_STATUS_TOKEN_EXPIRE = 'Token expired'; // 401
export const HTTP_STATUS_BAD_REQUEST = 'Bad request'; // 400
export const HTTP_STATUS_NOT_FOUND = 'Not found'; // 404
export const HTTP_STATUS_CONFLICT = 'Conflict error'; // 409
export const HTTP_STATUS_INTERNAL_SERVER = 'Internal server error'; // 500
export const ACCESS_TOKEN_KEY = 'Token_Key';
export const BASE_URL = 'https://devb2b.bizpoint-intl.com:3082';
export const SESSION_NAME = 'Sus-Plan';
