name: Development Deployment
on:
  push:
    branches: 
      - development

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Admin-Panel
    runs-on: ubuntu-latest
    env:
      MODE: "development"
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Create Environment File
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          token: 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
          path: 'src/config.js'
          openDelimiter : "MODE:"
          closeDelimiter : ",//MODE_END"
          body: '"production"'

      - name: 🔨 Install dependencies && Build Project
        run: |
          npm cache clean -f
          npm i --force
          npm run build

      # - name: 📂 Sync files to Development
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: braintechsolution.com
      #     username: bim-admin-dev@braintechsolution.com
      #     password: bim-admin-dev@Shik7061
      #     dangerous-clean-slate: true
      #     exclude: |
      #       **/.git*
      #       **/.github*
      #       **/.env*
      #       **/.git*/**
      #       **/node_modules/**
      #       **/public/**
      #       **/src/**
      #       package.json
      #       package-lock.json
      #       vite.config.js
      #       yarn.lock